title: 'logingrupa.storeextender::lang.group.list_title'
modelClass: Lovata\Buddies\Models\Group
list: $/logingrupa/storeextender/models/group/columns.yaml
recordUrl: 'logingrupa/storeextender/groups/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: '25'
showSetup: true
showCheckboxes: true
showSorting: 1
defaultSort:
  column: id
  direction: desc
toolbar:
  buttons: list_toolbar
  search:
    prompt: 'backend::lang.list.search_prompt'
